#!/bin/zsh

# This corresponds to plot 2 in step 3 of the assignment:
#    - Runtime divided by N3 vs optimization settings for all matrix sizes


# So what we need to do is run the same thing of what we did in plot 1 but for different sizes
# of N: N=256/512/1024/2048 -- we don't need to do 4096 again because we already did that in plot 1
# and running N=4096 takes a really long time

./buildall 256 && ./runall "results/plot2_`date +%s`/256"
./buildall 512 && ./runall "results/plot2_`date +%s`/512"
./buildall 1024 && ./runall "results/plot2_`date +%s`/1024"
./buildall 2048 && ./runall "results/plot2_`date +%s`/2048"