#!/bin/zsh

# This corresponds to plot 1 in step 3 of the assignment:
#    - Runtime vs optimization settings for a size 4096 matrix

N=4096
PP="results/mod/plot1"

mkdir -p $PP
mkdir -p out/mod
mkdir -p out

echo "Running 1/18" && \
make buildmod N_SIZE=$N && \
./out/mod/matmul > $PP/matmul.txt

echo "Running 2/18" && \
make buildmod-float N_SIZE=$N && \
./out/mod/matmul_f > $PP/matmul_f.txt

echo "Running 3/18" && \
make buildmod-double N_SIZE=$N && \
./out/mod/matmul_d > $PP/matmul_d.txt

echo "Running 4/18" && \
make buildmod-o N_SIZE=$N && \
./out/mod/matmul_o1 > $PP/matmul_o1.txt

echo "Running 5/18" && \
make buildmod-float-o N_SIZE=$N && \
./out/mod/matmul_f_o1 > $PP/matmul_f_o1.txt

echo "Running 6/18" && \
make buildmod-double-o N_SIZE=$N && \
./out/mod/matmul_d_o1 > $PP/matmul_d_o1.txt

echo "Running 7/18" && \
make buildmod-o2 N_SIZE=$N && \
./out/mod/matmul_o2 > $PP/matmul_o2.txt

echo "Running 8/18" && \
make buildmod-double-o3 N_SIZE=4096 && \
./out/mod/matmul_d_o4 > results/matmul_d_o3.txt &

echo "Running 9/18" && \
make buildmod-double-o2 N_SIZE=$N && \
./out/mod/matmul_d_o3 > $PP/matmul_d_o3.txt

echo "Running 10/18" && \
make buildmod-o3 N_SIZE=$N && \
./out/mod/matmul_o3 > $PP/matmul_o3.txt

echo "Running 11/18" && \
make buildmod-float-o3 N_SIZE=$N && \
./out/mod/matmul_f_o3 > $PP/matmul_f_o3.txt

echo "Running 12/18" && \
make buildmod-double-o3 N_SIZE=$N && \
./out/mod/matmul_d_o4 > $PP/matmul_d_o4.txt

echo "Running 13/18" && \
make buildmod-extra N_SIZE=$N && \
./out/mod/matmul_e > $PP/matmul_e.txt

echo "Running 14/18" && \
make buildmod-float-extra N_SIZE=$N && \
./out/mod/matmul_f_e > $PP/matmul_f_e.txt

echo "Running 15/18" && \
make buildmod-double-extra N_SIZE=$N && \
./out/mod/matmul_d_e > $PP/matmul_d_e.txt

echo "Running 16/18" && \
make buildmod-custom N_SIZE=$N && \
./out/mod/matmul_custom > $PP/matmul_custom.txt

echo "Running 17/18" && \
make buildmod-float-custom N_SIZE=$N && \
./out/mod/matmul_f_custom > $PP/matmul_f_custom.txt

echo "Running 18/18" && \
make buildmod-double-custom N_SIZE=$N && \
./out/mod/matmul_d_custom > $PP/matmul_d_custom.txt
