#!/bin/zsh
# This script runs all the compiled versions and then write results to file

if [ $# -eq 0 ]
then
    echo "Must supply 1 argument: Path to results?"
    echo "Must supply 1 argument: N_SIZE = ?"
    exit 1
fi

mkdir -p $2
mkdir -p out/mod

echo "Running 1/18" && \
make buildmod N_SIZE=$1 && \
./out/mod/matmul > $2/matmul.txt

echo "Running 2/18" && \
make buildmod-float N_SIZE=$1 && \
./out/mod/matmul_f > $2/matmul_f.txt

echo "Running 3/18" && \
make buildmod-double N_SIZE=$1 && \
./out/mod/matmul_d > $2/matmul_d.txt

echo "Running 4/18" && \
make buildmod-o N_SIZE=$1 && \
./out/mod/matmul_o1 > $2/matmul_o1.txt

echo "Running 5/18" && \
make buildmod-float-o N_SIZE=$1 && \
./out/mod/matmul_f_o1 > $2/matmul_f_o1.txt

echo "Running 6/18" && \
make buildmod-double-o N_SIZE=$1 && \
./out/mod/matmul_d_o1 > $2/matmul_d_o1.txt

echo "Running 7/18" && \
make buildmod-o2 N_SIZE=$1 && \
./out/mod/matmul_o2 > $2/matmul_o2.txt

echo "Running 8/18" && \
make buildmod-float-o2 N_SIZE=$1 && \
./out/mod/matmul_f_o2 > $2/matmul_f_o2.txt

echo "Running 9/18" && \
make buildmod-double-o2 N_SIZE=$1 && \
./out/mod/matmul_d_o3 > $2/matmul_d_o3.txt

echo "Running 10/18" && \
make buildmod-o3 N_SIZE=$1 && \
./out/mod/matmul_o3 > $2/matmul_o3.txt

echo "Running 11/18" && \
make buildmod-float-o3 N_SIZE=$1 && \
./out/mod/matmul_f_o3 > $2/matmul_f_o3.txt

echo "Running 12/18" && \
make buildmod-double-o3 N_SIZE=$1 && \
./out/mod/matmul_d_o4 > $2/matmul_d_o4.txt

echo "Running 13/18" && \
make buildmod-extra N_SIZE=$1 && \
./out/mod/matmul_e > $2/matmul_e.txt

echo "Running 14/18" && \
make buildmod-float-extra N_SIZE=$1 && \
./out/mod/matmul_f_e > $2/matmul_f_e.txt

echo "Running 15/18" && \
make buildmod-double-extra N_SIZE=$1 && \
./out/mod/matmul_d_e > $2/matmul_d_e.txt

echo "Running 16/18" && \
make buildmod-custom N_SIZE=$1 && \
./out/mod/matmul_custom > $2/matmul_custom.txt

echo "Running 17/18" && \
make buildmod-float-custom N_SIZE=$1 && \
./out/mod/matmul_f_custom > $2/matmul_f_custom.txt

echo "Running 18/18" && \
make buildmod-double-custom N_SIZE=$1 && \
./out/mod/matmul_d_custom > $2/matmul_d_custom.txt
