#!/bin/zsh
# This script runs all the compiled versions and then write results to file

mkdir -p results
rm results/*

echo "Running 1/18" && ./out/matmul >> results/matmul.txt
echo "Running 2/18" && ./out/matmul_f >> results/matmul_f.txt
echo "Running 3/18" && ./out/matmul_d >> results/matmul_d.txt
echo "Running 4/18" && ./out/matmul_o1 >> results/matmul_o1.txt
echo "Running 5/18" && ./out/matmul_f_o1 >> results/matmul_f_o1.txt
echo "Running 6/18" && ./out/matmul_d_o1 >> results/matmul_d_o1.txt
echo "Running 7/18" && ./out/matmul_o2 >> results/matmul_o2.txt
echo "Running 8/18" && ./out/matmul_f_o2 >> results/matmul_f_o2.txt
echo "Running 9/18" && ./out/matmul_d_o3 >> results/matmul_d_o3.txt
echo "Running 10/18" && ./out/matmul_o3 >> results/matmul_o3.txt
echo "Running 11/18" && ./out/matmul_f_o3 >> results/matmul_f_o3.txt
echo "Running 12/18" && ./out/matmul_d_o4 >> results/matmul_d_o4.txt
echo "Running 13/18" && ./out/matmul_e >> results/matmul_e.txt
echo "Running 14/18" && ./out/matmul_f_e >> results/matmul_f_e.txt
echo "Running 15/18" && ./out/matmul_d_e >> results/matmul_d_e.txt
echo "Running 16/18" && ./out/matmul_custom >> results/matmul_custom.txt
echo "Running 17/18" && ./out/matmul_f_custom >> results/matmul_f_custom.txt
echo "Running 18/18" && ./out/matmul_d_custom >> results/matmul_d_custom.txt