#!/bin/zsh
# This script runs all the compiled versions and then write results to file

if [ $# -eq 0 ]
then
    echo "Must supply 1 argument: Path to results?"
    echo "Must supply 1 argument: N_SIZE = ?"
    exit 1
fi

mkdir -p $2
mkdir -p out/mod

echo "Running 1/3" && \
make buildmod-custom N_SIZE=$1 && \
./out/mod/matmul_custom > $2/matmul_custom.txt

echo "Running 2/3" && \
make buildmod-float-custom N_SIZE=$1 && \
./out/mod/matmul_f_custom > $2/matmul_f_custom.txt

echo "Running 3/3" && \
make buildmod-double-custom N_SIZE=$1 && \
./out/mod/matmul_d_custom > $2/matmul_d_custom.txt
