#!/bin/zsh
# This script tests that the multiplication logic is correct

echo 'Now testing naive: Press any key to continue...'; read -k1 -s
make test-int N_SIZE=3 &&  ./out/matmul_test_int
make test-float N_SIZE=3 && ./out/matmul_test_float
make test-double N_SIZE=3 && ./out/matmul_test_double
echo 'Now testing tiled: Press any key to continue...'; read -k1 -s
make test-tiled-int N_SIZE=3 &&  ./out/matmul_test_tiled_int
make test-tiled-float N_SIZE=3 && ./out/matmul_test_tiled_float
make test-tiled-double N_SIZE=3 && ./out/matmul_test_tiled_double