#!/bin/zsh

# This is a script to explore and document flags and transformations
# that work for the loops

# Rewrite the “vanilla” code by manually applying typical
# compiler transformations, and applying the best custom
# flags you can find, for N=4096. As your results improve,
# plot performance (seconds) for each version (min 3 versions)
# Document the flags and the transformations that work.

# Controlled variables:
# N = 4096 (1024 at first)
# type is Float
# Modifying from the custom flags

# Version 1 (base / vanilla version)
make build-float-custom N_SIZE=1024
./out/matmul_f_custom
# 0.658661

# Vession 2 (Triple-tiled at tilesize of 512)
make build-float-custom N_SIZE=1024 EXTRA_DEFINES="-D MATMUL_TILED -D TILE_SIZE=512"
./out/matmul_f_custom
# 1.305483

# Version 3 (Manual loop unroll - 2)
make build-float-custom N_SIZE=1024 \
    EXTRA_DEFINES="-D MATMUL_DO2"
./out/matmul_f_custom
# 0.651673

# Version 4 (Manual loop unroll - 4)
make build-float-custom N_SIZE=1024 \
    EXTRA_DEFINES="-D MATMUL_DO4"
./out/matmul_f_custom
# 0.650896 This creates less branching

# Version 5 -- from 4 -- manually interchanging the outer loop
make build-float-custom N_SIZE=1024 \
    EXTRA_DEFINES="-D MATMUL_DO4_A"
./out/matmul_f_custom
# 0.653942 (worse)

# Version 5b -- from 4 -- manually interchanging the outer loop
make build-float-custom N_SIZE=1024 \
    EXTRA_DEFINES="-D MATMUL_DO4_B"
./out/matmul_f_custom
# 0.653942 (worse)

# (worse) -fgcse-lm -fgcse-sm

# Version 6 -- from 4
gcc -o out/matmul_f_custom matmul.c -Ofast -m64 -march=barcelona -mtune=barcelona -ftree-vectorize -fmerge-all-constants -fmodulo-sched -faggressive-loop-optimizations -floop-interchange -funroll-loops -ftree-loop-distribution -funswitch-loops -D USE_FLOAT -D N_SIZE=1024 -D MATMUL_DO4 \
&& for i in {1..5}; do ./out/matmul_f_custom; done | grep CLOCK=
# 0.652408

# Version 7 -- from 4
gcc -o out/matmul_f_custom matmul.c -Ofast -m64 -march=barcelona -mtune=barcelona -ftree-vectorize -fmerge-all-constants -fmodulo-sched -faggressive-loop-optimizations -floop-interchange -funroll-loops -ftree-loop-distribution -funswitch-loops -D USE_FLOAT -D N_SIZE=1024 -D MATMUL_DO4 \
--param 
&& for i in {1..5}; do ./out/matmul_f_custom; done | grep CLOCK=
